//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace steamBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("steamBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Click to \b select \b0 all games for backup.  The selection can be modified in the check box list. }.
        /// </summary>
        internal static string BackupAllButtonTooltip {
            get {
                return ResourceManager.GetString("BackupAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Cancels the backup procedure and navigates back to the main menu. }.
        /// </summary>
        internal static string BackupCancelButtonTooltip {
            get {
                return ResourceManager.GetString("BackupCancelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Customize your selection of games to backup.  \b NOTE: \b0 Older games that utilize Valve&apos;s Source Engine share resources between each other, However Valve has patched this out. Make sure you have the latest version of these old steam games, this tool will not be able to backup or restore them otherwise. }.
        /// </summary>
        internal static string BackupCheckListTooltip {
            get {
                return ResourceManager.GetString("BackupCheckListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Click to \b deselect \b0 all games for backup.  The selection can be modified in the check box list. }.
        /// </summary>
        internal static string BackupNoneButtonTooltip {
            get {
                return ResourceManager.GetString("BackupNoneButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Starts the backup procedure with the above parameters }.
        /// </summary>
        internal static string BackupStartButtonTooltip {
            get {
                return ResourceManager.GetString("BackupStartButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please exit Steam before backing up. To continue, exit Steam and then click the &apos;Backup&apos; button again. Do Not start Steam until the backup process is finished..
        /// </summary>
        internal static string BackupSteamRunningText {
            get {
                return ResourceManager.GetString("BackupSteamRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Level:
        ///.
        /// </summary>
        internal static string CompressionLevelText {
            get {
                return ResourceManager.GetString("CompressionLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi This will change how small the backup files are. Higher compression levels will use more ram and take longer but will result in far better compression. }.
        /// </summary>
        internal static string CompressionTooltip {
            get {
                return ResourceManager.GetString("CompressionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Hover your mouse over the controls to get further information. }.
        /// </summary>
        internal static string ControlsDefaultTooltip {
            get {
                return ResourceManager.GetString("ControlsDefaultTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi This will delete \b EVERYTHING \b0 in the &apos;Backup Directory&apos;. Make sure that there are no valuable files in there! }.
        /// </summary>
        internal static string DelBackupCheckBoxTooltip {
            get {
                return ResourceManager.GetString("DelBackupCheckBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed below are the errors for a backup or restore.
        ///
        ///Please try running the backup process again making sure that there are no programs accessing the files being backed up (e.g. Steam).
        ///
        ///To check the integrity of this backup: navigate to the backup location -&gt; Select all files in the &apos;common&apos; folder -&gt; right click -&gt; 7zip -&gt; Test archive. You should do the same for &apos;Source Games.7z&apos; also..
        /// </summary>
        internal static string ErrorListHeader {
            get {
                return ResourceManager.GetString("ErrorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the number of instances to run.
        ///Recommended: One instance for every two CPU cores..
        /// </summary>
        internal static string InstancesCountTooltip {
            get {
                return ResourceManager.GetString("InstancesCountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        /////////////////////// Error Time: {0} \\\\\\\\\\\\\\\\\\\\
        ///
        ///
        ///{1}.
        /// </summary>
        internal static string JobError {
            get {
                return ResourceManager.GetString("JobError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi This will use multi threaded compression and reduce concurrent compression instances to 1.  The compressed archives have similar sizes compared to LZMA compression. }.
        /// </summary>
        internal static string Lzma2CheckboxTooltip {
            get {
                return ResourceManager.GetString("Lzma2CheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Ram Usage: {0:g}MB.
        /// </summary>
        internal static string MaxRamUsageText {
            get {
                return ResourceManager.GetString("MaxRamUsageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Click to \b select \b0 all games in the list. The selection can be modified in the check box list. }.
        /// </summary>
        internal static string RestoreAllButtonTooltip {
            get {
                return ResourceManager.GetString("RestoreAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Cancels the restore procedure and navigates back to the main menu. }.
        /// </summary>
        internal static string RestoreCancelButtonTooltip {
            get {
                return ResourceManager.GetString("RestoreCancelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Customise your selection of games to restore.  \b NOTE: \b0 Older games that utilize Valve&apos;s Source Engine share resources between each other, However Valve has patched this out. Make sure you have the latest version of these old steam games, this tool will not be able to backup or restore them otherwise. }.
        /// </summary>
        internal static string RestoreCheckListTooltip {
            get {
                return ResourceManager.GetString("RestoreCheckListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Click to \b deselect \b0 all games in the list. The selection can be modified in the check box list. }.
        /// </summary>
        internal static string RestoreNoneButtonTooltip {
            get {
                return ResourceManager.GetString("RestoreNoneButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Allows for some games to be restored to a alternative library.  }.
        /// </summary>
        internal static string RestoreRefreshListLabelTooltip {
            get {
                return ResourceManager.GetString("RestoreRefreshListLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Starts the restore procedure with the above parameters. \b This will overwrite any currently installed Steam games with the back up files. \b0 }.
        /// </summary>
        internal static string RestoreStartButtonTooltip {
            get {
                return ResourceManager.GetString("RestoreStartButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please exit Steam before restoring. To continue, exit Steam and then click the &apos;Start Restore&apos; button again. Do Not start Steam until the restore process is finished..
        /// </summary>
        internal static string RestoreSteamRunningText {
            get {
                return ResourceManager.GetString("RestoreSteamRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi This will change how many threads are used. Doesn&apos;t use much ram and can only utilizes one core per instance. }.
        /// </summary>
        internal static string RestoreThreadsTooltip {
            get {
                return ResourceManager.GetString("RestoreThreadsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Is Running.
        /// </summary>
        internal static string SteamRunningTitle {
            get {
                return ResourceManager.GetString("SteamRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Instances:
        ///.
        /// </summary>
        internal static string ThreadLblInstancesText {
            get {
                return ResourceManager.GetString("ThreadLblInstancesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Threads:
        ///.
        /// </summary>
        internal static string ThreadLblThreadsText {
            get {
                return ResourceManager.GetString("ThreadLblThreadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the number of Threads to run.
        ///Recommended: One Thread for every CPU core..
        /// </summary>
        internal static string ThreadsCountTooltip {
            get {
                return ResourceManager.GetString("ThreadsCountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi This will change how many threads are used. It is recommended that you set the slider to \b &apos;core_count&apos; \b0 for best performance.  Dramatically increases ram usage when also using high compression rates.  }.
        /// </summary>
        internal static string ThreadsLzma2Tooltip {
            get {
                return ResourceManager.GetString("ThreadsLzma2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi This will change how many instances of 7zip are used, each instance creates two threads. It is recommended that you set the slider to \b &apos;core_count/2&apos; \b0 for best performance.  Dramatically increases ram usage when also using high compression rates. }.
        /// </summary>
        internal static string ThreadsLzmaTooltip {
            get {
                return ResourceManager.GetString("ThreadsLzmaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Click to select all games that have been changed since the last backup, \b Excluding \b0 games that have not been backed up yet.  The selection can be modified in the check box list. }.
        /// </summary>
        internal static string UpdateBackupButtonTooltip {
            get {
                return ResourceManager.GetString("UpdateBackupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Click to select all games that have been changed since the last backup, \b Including \b0 games that have not been backed up yet. The selection can be modified in the check box list. }.
        /// </summary>
        internal static string UpdateLibButtonTooltip {
            get {
                return ResourceManager.GetString("UpdateLibButtonTooltip", resourceCulture);
            }
        }
    }
}
